// constants/privileges.js
export const MODULES = {
  DASHBOARD: 1,
  USER_MANAGEMENT: 2,
  AGENT_ORG: 4,
  FORM_DESIGNER: 5,
  INTERACTION: 6,
  ROLE_MANAGEMENT: 7,
  ORGANIZATION: 8,
  REPORTS: 10,
  ORGANIZATION_FORM_MAPPING: 9,
};

export const PRIVILEGES = {
  VIEW: 1,
  CREATE: 2,
  EDIT: 3,
  DELETE: 5,
  CREATEEDITFORM: 10,
  VIEWSUBMITTEDFORM: 9,
  EVALUATEFORM: 8,
  USER_MANAGEMENT: 21,
  FORMS: 22,
  INTERACTION: 23,
  Agent_Dashboard: 24,
  DEASSOCIATE_ORG: 25,
};
