-- Create module-specific tables for Call Monitoring (new tables only)
-- Run these statements on your existing SQL Server database.

CREATE TABLE IF NOT EXISTS CallMonitoring_Calls (
  WebexCallId UNIQUEIDENTIFIER PRIMARY KEY,
  AgentId NVARCHAR(100) NULL,
  AgentName NVARCHAR(255) NULL,
  QueueName NVARCHAR(255) NULL,
  Status NVARCHAR(100) NULL,
  Direction NVARCHAR(50) NULL,
  DurationSeconds INT NULL,
  StartedAt DATETIME2 NULL,
  EndedAt DATETIME2 NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  raw NVARCHAR(MAX) NULL
);

CREATE TABLE IF NOT EXISTS CallMonitoring_Agents (
  AgentId NVARCHAR(100) PRIMARY KEY,
  AgentName NVARCHAR(255) NULL,
  Status NVARCHAR(100) NULL,
  CurrentCallId UNIQUEIDENTIFIER NULL,
  LastUpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  raw NVARCHAR(MAX) NULL
);

CREATE TABLE IF NOT EXISTS CallMonitoring_CallLogs (
  LogId INT IDENTITY(1,1) PRIMARY KEY,
  WebexCallId UNIQUEIDENTIFIER NULL,
  EventType NVARCHAR(100) NULL,
  EventPayload NVARCHAR(MAX) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE IF NOT EXISTS CallMonitoring_Alerts (
  AlertId INT IDENTITY(1,1) PRIMARY KEY,
  WebexCallId UNIQUEIDENTIFIER NULL,
  AlertType NVARCHAR(100) NOT NULL,
  Description NVARCHAR(1000) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  ResolvedAt DATETIME2 NULL
);

CREATE TABLE IF NOT EXISTS CallMonitoring_Scores (
  ScoreId INT IDENTITY(1,1) PRIMARY KEY,
  WebexCallId UNIQUEIDENTIFIER NULL,
  ScoreValue INT NOT NULL,
  RuleSet NVARCHAR(255) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  Raw NVARCHAR(MAX) NULL
);

CREATE TABLE IF NOT EXISTS CallMonitoring_Transcripts (
  TranscriptId INT IDENTITY(1,1) PRIMARY KEY,
  WebexCallId UNIQUEIDENTIFIER NULL,
  TranscriptText NVARCHAR(MAX) NULL,
  Source NVARCHAR(255) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE IF NOT EXISTS CallMonitoring_Recordings (
  RecordingId INT IDENTITY(1,1) PRIMARY KEY,
  WebexCallId UNIQUEIDENTIFIER NULL,
  PlaybackUrl NVARCHAR(MAX) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
